version: '3.9'

services:
  test-inside:
    depends_on:
      - test-db
    build:
      context: .
    environment:
      - DB_USER_LOCAL=${DB_USER_LOCAL}
      - DB_PASSWORD_LOCAL=${DB_PASSWORD_LOCAL}
      - TOKEN_SECRET=${TOKEN_SECRET}
    ports:
      - "1024:1024"
    restart: always
  test-db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: ${DB_USER_LOCAL}
      POSTGRES_PASSWORD: ${DB_PASSWORD_LOCAL}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
